services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    command: ["sh", "-c", "chmod -R 777 /data/db && mongod --bind_ip_all"]
    networks:
      - mynetwork
    volumes:
      - ./mongo_data:/data/db
  fastapi:
    image: python:latest
    working_dir: /fastapi
    volumes:
      - ./fastapi:/fastapi
    command: sh -c "pip install -r requirements.txt && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - 8000:8000
    networks:
      - mynetwork
  next:
    image: node:lts-alpine
    working_dir: /next
    volumes:
      - ./next:/next
    command: sh -c "npm install && npm run dev"
    ports:
      - 3000:3000
    networks:
      - mynetwork

networks:
  mynetwork: